### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by kpspivey**
Fixed typo - pubic to public

### CODE REVIEW

**Comment by kpspivey** [comment]
FYI, I got this note:

<http://circleci.com/>
*ci/circleci *— Your tests failed on CircleCI
Required


so I can't squash and merge.

Katherine Spivey
Web/Social Media Manager
QT1DCA – Outreach Analysis & Digital Media Branch

GSA's Plain Language Office
katherine.spivey@gsa.gov

**Comment by hursey013** [comment]
Yeah 🙁, I'm hoping it's just something temporary, I will try resubmitting it shortly and hopefully that'll take care of it.

**Comment by hursey013** [comment]
Ok, self corrected, merging this in.

**Comment by MEVincentPL** [comment]
Thanks Brian!

Miriam Vincent
Staff Attorney, Legal Affairs and Policy Division
Office of the Federal Register
National Archives and Records Administration
(o)202.741.6024 (bb) 202.276.3219

**Pull request merged**
