### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by MEVincentPL**
Adding sitewide notice about gov't shutdown

### CODE REVIEW

**Comment by kpspivey** [comment]
approved - kps

**Comment by hursey013** [comment]
@kpspivey Did you mean to merge this in? It was closed and at this point has not been merged into the live site. I believe you can still reopen this same pull request and merge it in if that was your original intent.

**Comment by kpspivey** [comment]
I thought I'd merged it.

**Comment by kpspivey** [comment]
I'm still waiting on the federalist/build

**Comment by hursey013** [comment]
@kpspivey Ok, I restarted the federalist build and it looks like it's good now.

**Comment by MEVincentPL** [comment]
@kpspivey  @hursey013  Thanks!  One of these days we'll manage to do it right the first time.

**Comment by kpspivey** [comment]
And I squashed and merged. Shall I delete the branch?

Katherine Spivey
Web/Social Media Manager
QT1DCA – Outreach Analysis & Digital Media Branch

GSA's Plain Language Office
katherine.spivey@gsa.gov

**Comment by hursey013** [comment]
@kpspivey, yes once it's merged in you are safe to delete the branch.

@MEVincentPL you all did everything right. There is an outstanding federalist issue that causes the builds to hang which prevents them from being merged in. I'll follow up with the team so hopefully it can get addressed and not happen again.

**Comment by kpspivey** [comment]
Thank heavens! A time we can legitimately blame the technology.

Katherine Spivey
Web/Social Media Manager
QT1DCA – Outreach Analysis & Digital Media Branch

GSA's Plain Language Office
katherine.spivey@gsa.gov

**Comment by kpspivey** [comment]
So I was attempting to upate the meeting info for February, and

My test failed on CircleCL - so I'm not sure what I did wrong. Sorry I'm
not immediately brilliant at this.

And of course merging is blocked.

Katherine Spivey
Web/Social Media Manager
QT1DCA – Outreach Analysis & Digital Media Branch

GSA's Plain Language Office
katherine.spivey@gsa.gov

**Pull request merged**
