### PR TITLE
Update install instructions

### LINKED ISSUE #216: Issue with Jekyll compilation on macos
__Issue would return an error involving "basscss" not being found__

Need better detail as to *how* to compile/install an equivalent of 'plainlanguage.gov'.

For macos (I am currently running macos 10.14.6 (Mojave), the missing piece is to install via 'brew'.

If anyone has any suggested method of compilation/installation, please post it here.  Thx!

### PR DESCRIPTION
**Pull request by saracope**
Add additional info to install instructions in README.md.

Closes #216

### CODE REVIEW

**Comment by saracope** [comment]
@jcastle Mind testing this install instructions?

**Review by jcastle — CHANGES_REQUESTED** [review]
@saracope, I reviewed and add changes to the PR. If you agree, go ahead and merge or send back some ideas. BTW, Pa11y is failing at http://localhost:4000/training/videos with “Iframe element requires a non-empty title attribute that identifies the frame.” Rest of training and media URLs are aborted. Search url passes. 190 of 200 tests pass. I will look at these tests too but not as familiar with Pa11y config so may need some help.

**Comment by jcastle** [comment]
@saracope 

BTW, looking at labels. We can come up with one set of labels for all repos. It is possible to setup one repo with what we want and then copy to the other repos. Also, do you want to create one repo like https://github.com/GSA/code-gov as a pointer and master repo?

**Comment by jcastle** [comment]
Fixed the iFrame title issue but having issues with media files. Will continue to research and update in separate feature branch.

**Pull request merged**
