### PR TITLE
 updated webpack@5.72.0

### PR DESCRIPTION
**Pull request by aalikaram**

### CODE REVIEW

**Review by matthewbogdan — COMMENTED** [review]
Your build is failing here: [webpack-cli] Error: Unknown option '--colors'
It's in the build scripts in the package.json file:
    `"build-js": "webpack --config --progress --colors",`
This seems like a known issue:
    https://github.com/rails/webpacker/issues/3138

**Comment by mejiaj** [comment]
Updating webpack requires additional steps.

- [ ] Remove `--colors` flag
- [ ] Update `webpack.config.js` to new syntax

**Comment by nick-mon1** [comment]
[babel-preset-es2015](https://babeljs.io/docs/en/babel-preset-es2015/) is deprecated in favor of [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env) and have updated to babel 7.17.10 to get this work with webpack 5.

**Review by mejiaj — APPROVED** [review]
Nice job! I was able to successfully run the `build-js` and `watch-js` webpack tasks without any issues.

The errors from `731cba3` and earlier were also reproducible, since Babel hadn't been updated at that point.

**Pull request merged**
